#ifndef TICTACTOE_SERVER_HTTP_METHODS_H
#define TICTACTOE_SERVER_HTTP_METHODS_H

enum class HttpMethod {
    GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD, CONNECT, TRACE
};

#endif //TICTACTOE_SERVER_HTTP_METHODS_H
